---
name: Michael D.
surname: Anderson
position: "Data Scientist"
address: "Louisville, Kentucky"
phone: 502.415.0709
email: "mda2894@gmail.com"
github: mda2894
linkedin: mda2894
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::awesomecv
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tibble)
```

$~$

# Education

```{r}
tribble(
  ~ degree, ~ year, ~ institution, ~ where, ~ details,
  "Graduate Certificate in Biostatistics, Post-Graduate Studies in Public Health", "August 2018 - May 2020", "University of Kentucky", "Lexington, KY", "Recipient of full-time graduate assistantship, including full tuition scholarship",
  
  "Graduate Certificate in Biostatistics, Post-Graduate Studies in Public Health", "August 2018 - May 2020", "University of Kentucky", "Lexington, KY", "Primary course of study focused on application of statistical methods to public health research, including coursework in data mining, longitudinal data analysis, generalized linear models, nonparametric statistics, causal inference, epidemiology, and statistical genetics",
  
    "Graduate Certificate in Biostatistics, Post-Graduate Studies in Public Health", "August 2018 - May 2020", "University of Kentucky", "Lexington, KY", "Performed independent research into the development of novel nonparametric regression techniques",
  
  "Master of Science in Statistics", "August 2016 - May 2018", "University of Kentucky", "Lexington, KY", "Recipient of full-time graduate assistantship, including full tuition scholarship",
  
  "Master of Science in Statistics", "August 2016 - May 2018", "University of Kentucky", "Lexington, KY", "Primary course of study focused on advanced statistical theory and application, including coursework in machine learning, computational statistics, advanced data analysis, clinical trials, survival analysis, and experimental design",
  
  "Bachelor of Science in Mathematical Economics", "August 2012 - May 2016", "University of Kentucky", "Lexington, KY", "Summa Cum Laude, Departmental Honors",
  
  "Bachelor of Science in Mathematical Economics", "August 2012 - May 2016", "University of Kentucky", "Lexington, KY", "Recipient of Academic Excellence Scholarship and Alumni Collegiate Plate Scholarship",
  
  "Bachelor of Science in Mathematical Economics", "August 2012 - May 2016", "University of Kentucky", "Lexington, KY", "Officer of UK Economics Society, founding member of UK Quiz Bowl team",
  
  "Bachelor of Science in Mathematical Economics", "August 2012 - May 2016", "University of Kentucky", "Lexington, KY", "Primary course of study focused on quantitative methods in economics, including coursework in game theory, econometrics, and computer programming, with graduate-level coursework in probability, statistical inference, quantitative economics, and symbolic logic"
) %>% 
  detailed_entries(degree, year, institution, where, details)
```

$~$

# Experience

```{r}
tribble(
  ~ position, ~ year, ~ institution, ~ where, ~ details,
  
  "Data Analyst", "December 2021 - Present", "Strategic Marketing", "Louisville, KY", "Managed business database and statistical analytics for a data-driven, automotive marketing firm with hundreds of clients around the country",
  
  "Data Analyst", "December 2021 - Present", "Strategic Marketing", "Louisville, KY", "Integrated client data and external marketing data with business database, while maintaining data integrity and security, as well as consumer privacy and confidentiality",
  
  "Data Analyst", "December 2021 - Present", "Strategic Marketing", "Louisville, KY", "Performed database analytics for clients, to help them better understand their own data, and created performance analytics for multi-channel marketing campaigns, including direct mail, email, and digital and social media marketing, to demonstrate campaign efficacy",
  
  "Financial Data Transcriber", "January 2021 - December 2021", "JPMorgan Chase", "Louisville, KY", "Handled highly confidential taxpayer data at a high-security IRS processing facility, managed by JPMorgan Chase",
  
  "Financial Data Transcriber", "January 2021 - December 2021", "JPMorgan Chase", "Louisville, KY", "Duties included: extracting, processing, and balancing taxpayer data in the form of tax returns and payments; ensuring quick and accurate data entry into IRS database; training and assisting other staff in proper data processing and security protocols",
  
  "Graduate Assistant - Departments of Statistics and Biostatistics", "August 2016 - May 2020", "University of Kentucky", "Lexington, KY", "Performed research duties for healthcare researchers in the University's Center for Clinical and Translational Sciences (CCTS), and professors in the Department of Health Management and Policy",
  
  "Graduate Assistant - Departments of Statistics and Biostatistics", "August 2016 - May 2020", "University of Kentucky", "Lexington, KY", "Led multiple statistical programming workshops in R and SAS through the University's Quantitative Initiative for Policy and Social Research (QIPSR) and the Biostatistics, Epidemiology, and Research Design (BERD) core of the CCTS, including workshops on introductory programming, data analysis, data visualization, and survival analysis",
  
  "Graduate Assistant - Departments of Statistics and Biostatistics", "August 2016 - May 2020", "University of Kentucky", "Lexington, KY", "Taught my own section of STA 296 (undergraduate course in statistical methods) as the primary instructor, which included preparing lecture material, assignments, and exams for a class of over 30 students, as well as providing in-person and online tutoring hours for all STA 296 students (over 750 in total each semester)",
  
  "Graduate Assistant - Departments of Statistics and Biostatistics", "August 2016 - May 2020", "University of Kentucky", "Lexington, KY", "Assisted primary instructors on undergraduate courses in statistics and biostatistics, as well as graduate courses in bayesian data analysis, survival analysis, generalized linear models, and public health biostatistics"
) %>% 
  detailed_entries(position, year, institution, where, details)
```

\newpage

# Skills

**Programming**

- R, SQL, Python, C, HTML & CSS, Java, Javascript

**Software**

- RStudio & R Markdown, SAS, Stata, SPSS, Git & GitHub, Jupyter Notebook, Microsoft Office & Excel, LaTeX, Tableau, Amazon Web Services

$~$

Portfolio with programming and scientific writing samples available on my GitHub, linked above
